#!/bin/bash
pip3 install -r /requirements.txt
touch /usr/local/lib/python3.6/dist-packages/test-easy-install-16.write-test
#chown -R intelmq:intelmq /opt/dev_intelmq/
chown -R intelmq:intelmq /opt/intelmq/
usermod www-data -a -G intelmq
cp /opt/dev_intelmq/intelmq/bots/BOTS /opt/intelmq/etc/BOTS 
chmod -R g+w  /opt/intelmq
cd /opt/dev_intelmq && pip3 install -e .
su - intelmq -s /bin/bash -c 'intelmqctl upgrade-config'
$@
