#!/bin/bash

function check_config_files {

	echo "Checking for configuration files"
	for i in $(find /intelmq-bots/etc/ -name "*.conf"); do
		if [[ ! -f /opt/intelmq/etc/$(basename $i) ]]; then
			cp $i /opt/intelmq/etc/;
		fi;
	done;
	if [[ ! -f /opt/intelmq/etc/manager/positions.conf ]]; then
			cp -a /intelmq-bots/etc/manager /opt/intelmq/etc/;
	fi;
	chown -R intelmq.www-data /opt/intelmq/etc/;

 }

if [[ ! -z "${DEV}" ]]; then
  update
else
	echo "Mixing bots"
	if [[ ! -z "${REPO_UPDATE}" ]]; then
		rm -fr /intelmq-bots
		git clone ${REPO_UPDATE}
		cp -a intelmq-bots/bots/BOTS /opt/intelmq/etc/
		check_config_files
		update
	else
		check_config_files
	fi
fi

$@
