#!/bin/bash
cp -a /intelmq-bots/bots/* /opt/dev_intelmq/intelmq/bots/
cd /opt/dev_intelmq && pip3 install -e .
cp /opt/dev_intelmq/intelmq/bots/BOTS  /opt/intelmq/etc/BOTS
for file in $(find /intelmq-bots/ -name "*REQUIREMENTS.txt"); do pip3 install -r $file; done
su - intelmq -s /bin/bash -c 'intelmqctl upgrade-config'

